default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: elisha
  password: +q[@4LBn500S#mJ

development:
  <<: *default
  port: 4044
  database: elisha

  
test:
  <<: *default
  database: contacts_app_test

production:
  <<: *default
  database: contacts_app_production
  username: contacts_app
  password: <%= ENV["CONTACTS_APP_DATABASE_PASSWORD"] %>
