default: &default
  adapter: postgresql
  timeout: 60
  pool: 1

development:
  <<: *default
  port: 4044
  password: +q[@4LBn500S#mJ
  username: elisha
  database: elisha

production:
  <<: *default
